<?php

//! Add our ACF Custom Fields
add_action( 'admin_menu', function() {

    if ( function_exists('acf_add_local_field_group') ):

        // Add "Event Details" field group
        acf_add_local_field_group(array (
            'key' => 'group_557b6dfa634e0',
            'title' => 'Event Details',
            'fields' => array (
                array (
                    'key' => 'field_557b740dba9a1',
                    'label' => 'What type of event is this?',
                    'name' => 'event_type',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'Session' => 'Session',
                        'Keynote' => 'Keynote',
                        'Social Event' => 'Social Event',
                        'Auditorium' => 'Auditorium',
                        'Break' => 'Break',
                        'Food' => 'Food',
                        'Other' => 'Other',
                    ),
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => 'Session',
                    'layout' => 'horizontal',
                ),
                array (
                    'key' => 'field_557b737a37179',
                    'label' => 'Date',
                    'name' => 'event_date',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'Ymd',
                    'first_day' => 0,
                ),
                array (
                    'key' => 'field_557b720fb29cb',
                    'label' => 'Start Hour',
                    'name' => 'event_start_hour',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        7 => '7 am',
                        8 => '8 am',
                        9 => '9 am',
                        10 => '10 am',
                        11 => '11 am',
                        12 => '12 pm',
                        13 => '1 pm',
                        14 => '2 pm',
                        15 => '3 pm',
                        16 => '4 pm',
                        17 => '5 pm',
                        18 => '6 pm',
                        19 => '7 pm',
                        20 => '8 pm',
                        21 => '9 pm',
                        22 => '10 pm',
                    ),
                    'default_value' => array (
                        '' => '',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 1,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array (
                    'key' => 'field_557b72eab29cd',
                    'label' => 'Start Minute',
                    'name' => 'event_start_minute',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        '00' => '00',
                        15 => 15,
                        30 => 30,
                        45 => 45,
                    ),
                    'default_value' => array (
                        '' => '',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 1,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array (
                    'key' => 'field_557b72d4b29cc',
                    'label' => 'End Hour',
                    'name' => 'event_end_hour',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        7 => '7 am',
                        8 => '8 am',
                        9 => '9 am',
                        10 => '10 am',
                        11 => '11 am',
                        12 => '12 pm',
                        13 => '1 pm',
                        14 => '2 pm',
                        15 => '3 pm',
                        16 => '4 pm',
                        17 => '5 pm',
                        18 => '6 pm',
                        19 => '7 pm',
                        20 => '8 pm',
                        21 => '9 pm',
                        22 => '10 pm',
                    ),
                    'default_value' => array (
                        '' => '',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 1,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array (
                    'key' => 'field_557b72feb29ce',
                    'label' => 'End Minute',
                    'name' => 'event_end_minute',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        '00' => '00',
                        15 => 15,
                        30 => 30,
                        45 => 45,
                    ),
                    'default_value' => array (
                        '' => '',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 1,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array (
                    'key' => 'field_557eef700d873',
                    'label' => 'Which room is the session in?',
                    'name' => 'event_session_room',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Session',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        1 => 1,
                        2 => 2,
                    ),
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                ),
                array (
                    'key' => 'field_558f6728e1097',
                    'label' => 'Session Slides URL',
                    'name' => 'session_slides_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Session',
                            ),
                        ),
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Keynote',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array (
                    'key' => 'field_558f6700e1096',
                    'label' => 'Session Slides File',
                    'name' => 'session_slides_file',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Session',
                            ),
                        ),
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Keynote',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array (
                    'key' => 'field_558ea5dd10a22',
                    'label' => 'Session Feedback URL',
                    'name' => 'session_feedback_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Session',
                            ),
                        ),
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Keynote',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array (
                    'key' => 'field_557b6dffad2f8',
                    'label' => 'Learning Objectives',
                    'name' => 'learning_objectives',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Session',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => '',
                    'max' => '',
                    'layout' => 'table',
                    'button_label' => 'Add Objective',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_557b6e11ad2f9',
                            'label' => 'Learning Objective',
                            'name' => 'learning_objective',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                ),
                array (
                    'key' => 'field_557c7cc06a8d7',
                    'label' => 'Speakers',
                    'name' => 'speakers',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '==',
                                'value' => 'Session',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => '',
                    'max' => '',
                    'layout' => 'block',
                    'button_label' => 'Add Speaker',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_557c7cd36a8d8',
                            'label' => 'Name',
                            'name' => 'speaker_name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_557c7ceb6a8d9',
                            'label' => 'Institution',
                            'name' => 'speaker_institution',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_557c7cfd6a8da',
                            'label' => 'Institution Website',
                            'name' => 'speaker_institution_website',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array (
                            'key' => 'field_557c7d206a8db',
                            'label' => 'Position',
                            'name' => 'speaker_position',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_557c7d3b6a8dc',
                            'label' => 'Twitter',
                            'name' => 'speaker_twitter_handle',
                            'type' => 'text',
                            'instructions' => 'Do NOT include the @.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_557c7d516a8dd',
                            'label' => 'Website',
                            'name' => 'speaker_website',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array (
                            'key' => 'field_557c7d696a8de',
                            'label' => 'Photo',
                            'name' => 'speaker_photo',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_557c7d816a8df',
                            'label' => 'Biography',
                            'name' => 'speaker_biography',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ),
                    ),
                ),
                array (
                    'key' => 'field_55839ac3aa742',
                    'label' => 'Location',
                    'name' => 'event_location',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '!=',
                                'value' => 'Session',
                            ),
                            array (
                                'field' => 'field_557b740dba9a1',
                                'operator' => '!=',
                                'value' => 'Auditorium',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'schedule',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
        ));

    endif;

});